# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: VS Code Cppcheck
description: Run Cppcheck on your C and C++ code.
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "" # the base hostname & protocol for your site, e.g. http://example.com
# url: https://just-the-docs.github.io
github_username: brobeson
# show_downloads: true
markdown: kramdown
# toc: true
# layout: single

# Build settings
# remote_theme: pages-themes/midnight@v0.2.0
# theme: minima
# plugins:
#   - jekyll-remote-theme
#   - jekyll-feed
remote_theme: just-the-docs/just-the-docs@main
# theme: just-the-docs

aux_links:
  # Marketplace: https://marketplace.visualstudio.com/items?itemName=brobeson.ctest-lab
  Repository: https://github.com/brobeson/vscode-cppcheck
nav_external_links:
  - title: Issues
    url: https://github.com/brobeson/vscode-cppcheck/issues
color_scheme: dark
callouts:
  warning:
    title: Warning
    color: red
